webtalk_init -webtalk_dir E:/Engineering/Semester 2/Computer Organization and Digital Design/Labs/Lab 09 Submission/Nanoprocessor_04/Nanoprocessor_04.sim/sim_1/behav/xsim/xsim.dir/TB_Nanoprocessor_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Aug 17 19:16:48 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "78f4ec8e-712a-4bdb-bd5b-0fbb20a66e96" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "5749488a50a44613a411312338dfe606" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "61" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "11th Gen Intel(R) Core(TM) i3-1115G4 @ 3.00GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2995 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.03_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6528_KB" -context "xsim\\usage"
webtalk_transmit -clientid 100275826 -regid "" -xml E:/Engineering/Semester 2/Computer Organization and Digital Design/Labs/Lab 09 Submission/Nanoprocessor_04/Nanoprocessor_04.sim/sim_1/behav/xsim/xsim.dir/TB_Nanoprocessor_behav/webtalk/usage_statistics_ext_xsim.xml -html E:/Engineering/Semester 2/Computer Organization and Digital Design/Labs/Lab 09 Submission/Nanoprocessor_04/Nanoprocessor_04.sim/sim_1/behav/xsim/xsim.dir/TB_Nanoprocessor_behav/webtalk/usage_statistics_ext_xsim.html -wdm E:/Engineering/Semester 2/Computer Organization and Digital Design/Labs/Lab 09 Submission/Nanoprocessor_04/Nanoprocessor_04.sim/sim_1/behav/xsim/xsim.dir/TB_Nanoprocessor_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
